window.translations = window.translations || {};
window.translations['zh-hk'] = {
    subtitle: "遊戲數據實時監控與分析系統",
    version: "系統版本 v3.3.0 (分離式語言包) | 遠程醫療支援",
    nursingNotes: "💬 護理通訊錄",
    noLogs: "暫無留言記錄...",
    roleLabel: "身分：",
    roleNurse: "👩‍⚕️ 護理師",
    roleDoctor: "👨‍⚕️ 主治醫師",
    roleTherapist: "🧘 復健師",
    roleFamily: "🏠 家屬",
    sendBtn: "發送",
    deviceCenter: "📱 設備管理中心",
    genReport: "📄 生成醫療報告",
    searchingDev: "正在搜尋 Firebase 中的設備...",
    remoteCtrl: "遠程控制",
    diffLabel: "難度:",
    cumulativeData: "📊 累計數據",
    totalSessions: "總遊玩次數",
    highScore: "最高分",
    recentPerf: "📈 近期表現",
    latestSession: "🎯 最新一局",
    scoreLabel: "分數",
    statusLabel: "狀態:",
    waitingData: "等待數據...",
    detailedRecords: "📋 詳細記錄清單",
    colTime: "時間",
    colMode: "模式",
    colScore: "分數",
    colDuration: "耗時",
    selectDevPrompt: "請選擇設備...",
    lastUpdate: "最後更新",
    
    // Modal & Report
    rptModalTitle: "📋 認知訓練分析報告",
    rptUser: "受測設備/使用者：",
    rptTime: "報告生成時間：",
    rptCount: "數據樣本數：",
    rptSessions: "局",
    rptAnalysisHeader: "📊 綜合表現分析",
    rptSuggestionHeader: "💡 醫師/AI 建議 (Rule-based)",
    rptLogHeader: "📝 近期護理留言記錄",
    rptDisclaimer: "本報告由 Memory Bloom 系統自動生成，僅供參考，不作為正式醫療診斷依據。",
    btnClose: "關閉",
    btnDownload: "📥 下載 PDF 報告",
    
    // Dynamic Strings
    modeMem: "記憶模式",
    modeCnt: "計數模式",
    uploadSuccess: "上傳成功",
    savedLocally: "本地保存",

    // Report Logic Text
    rptSummaryStart: "根據系統監測，長者在近期共進行了 ",
    rptSummaryMid: " 次認知復健訓練。最近 5 次訓練的平均準確度評分為 ",
    rptProgress: " 數據顯示長者的短期記憶與反應力有回升跡象（提升約 ",
    rptProgressSugg1: "🧠 認知強化：建議維持目前的互動頻率，適度給予讚美以增強長者的自信心。",
    rptProgressSugg2: "💪 難度調整：若長者表現輕鬆，可嘗試微調至 'Auto' 或 'Hard' 模式以提供適當的認知刺激。",
    rptDecline: " 近期認知表現出現波動，準確率較前一階段下降。對於阿茲海默症患者，這可能與情緒焦慮、睡眠品質或生理不適有關。",
    rptDeclineSugg1: "❤️ 情緒安撫：請觀察長者是否有焦慮或「日落症候群 (Sundowning)」現象，訓練時請保持耐心，避免強迫。",
    rptDeclineSugg2: "📅 生活規律：建議固定訓練時間，建立穩定的生活作息有助於穩定認知狀態。",
    rptStable: " 認知狀態保持穩定。對於神經退化性疾病而言，「不退步」即是相當正面的指標，顯示目前的照護與訓練策略有效。",
    rptStableSugg1: "✅ 持續復健：請繼續鼓勵長者每日進行少量多次的練習，保持大腦活躍度。",
    rptStableSugg2: "🏠 環境支持：確保訓練環境安靜、光線充足，減少分心因素。",
    rptBaseline: " 系統正在建立個人的認知基準線 (Baseline)。持續的數據積累將有助於更精準地評估病情發展。",
    rptBaselineSugg: "ℹ️ 建立習慣：初期建議以「陪伴」為主，讓長者熟悉設備操作，減少對科技產品的排斥感。",
    rptLowScore: "⚠️ 狀態關注：最新一次訓練分數較低，請確認長者是否疲勞或身體不適。",

    // Placeholders
    inputPlaceholder: "在此輸入設備狀況、筆記或交接事項..."
};
